version: '3.8'

services:
  calculator:
    build:
      context: ./JavaWebCalculator
    container_name: calculoter
    ports:
      - "8081:8080"

  profile:
    build:
      context: ./vprofile-project
    container_name: name
    ports:
      - "8082:8080"  # Assuming vprofile exposes 8080 internally

petstor:
   build:
     context: ./jpetstore-6
    container_name: petstor
    ports: 
     - "8083:8080"
