version: '3.8'

services:
  calculator:
    build:
      context: ./calculator
    container_name: calculotr
    ports:
      - "8081:8080"

  profile:
    build:
      context: ./profile
    container_name: name
    ports:
      - "8082:8080"  # Assuming vprofile exposes 8080 internally

  petstore:
    build:
     context: ./petstore
    container_name: petstor
    ports: 
      - "8083:8080"
